apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  containers:
  - name: squid
    image: local/squid:5
    env:
    - name: ALLOWED_DOMAINS
      value: ".baidu.com .github.com"

  - name: alpine
    image: alpine
    command: ["sleep", "9999999"]
    env:
    - name: http_proxy
      value: http://localhost:3128
    - name: https_proxy
      value: http://localhost:3128
    - name: no_proxy
      value: "localhost,127.0.0.1"
